### PR TITLE
Build 2.6.7

### PR DESCRIPTION
**Pull request by pierrsc**
- I am trying to use a tool that depends on this exact version of markdown, which is currently missing from conda-forge

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pierrsc** [comment]
@conda-forge-admin, please rerender

**Comment by pierrsc** [comment]
@philip-khor, could you merge this? I really need this specific version of markdown in order for another of my packages.

**Comment by xhochy** [comment]
@philip-khor I would suggest to make a branch on the feedstock branching from master and then merge this PR to that branch. Builds on all branches are uploaded to anaconda.org

Otherwise you could also merge this master and the autotick bot will simply override this once a version is released.

**Comment by philip-khor** [comment]
> @philip-khor I would suggest to make a branch on the feedstock branching from master and then merge this PR to that branch. Builds on all branches are uploaded to anaconda.org
> 
> Otherwise you could also merge this master and the autotick bot will simply override this once a version is released.

Thanks @xhochy, I'll take the first approach. 

@pierrsc sorry for the delay, the PR looks fine to me, will merge into 2.6.7 branch.

**Review by philip-khor — APPROVED** [review]

**Comment by pierrsc** [comment]
Thank you!

**Pull request merged**
